spring.application.name=kafka

spring.datasource.url=jdbc:h2:mem:kafka;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=demo-group
spring.kafka.consumer.auto-offset-reset=earliest

app.kafka.topics.order=order
app.kafka.groups.order-processor=order-processor-group
app.kafka.groups.order-audit=order-audit-group
app.kafka.groups.email=email-group
app.kafka.groups.sms=sms-group
app.kafka.groups.push=push-group

app.outbox.publisher.fixed-delay-ms=3000
app.outbox.publisher.batch-size=25
app.outbox.publisher.max-retries=5
app.outbox.publisher.retry-backoff-ms=15000
app.outbox.publisher.ack-timeout-ms=5000

